var RLANG = {
	html: 'HTML',
	video: 'Video',
	image: 'Gambar',
	table: 'Tabel',
	link: 'Tautan',
	link_insert: 'Sisipkan tautan ...',
	unlink: 'Hapus tautan',
	styles: 'Tampilan',
	paragraph: 'Paragraf',
	quote: 'Kutipan',
	code: 'Kode',
	header1: 'Header 1',
	header2: 'Header 2',
	header3: 'Header 3',
	header4: 'Header 4',
	format: 'Format',
	bold:  'Tebal',
	italic: 'Miring',
	superscript: 'Tulis diatas',
	strikethrough: 'Coret',
	fontcolor: 'Warna font',
	backcolor: 'Warna belakang',
	removeformat: 'Hapus format',
	cleanstyles: 'Bersihkan tampilan',
	lists: 'Daftar',
	unorderedlist: 'Taftar tak berurutan',
	orderedlist: 'Berdasarkan daftar',	
	outdent: 'Keluarkan',
	indent: 'Masukkan',
	redo: 'Ulangi',
	undo: 'Mundur',
	cut: 'Potong',
	cancel: 'Batal',	
	insert: 'Sisipkan',
	save: 'Simpan',	
	_delete: 'Hapus',
	insert_table: 'Sisipkan tabel',		
	insert_row_above: 'Tambahkan baris di atas',
	insert_row_below: 'Tambahkan baris di bawah',
	insert_column_left: 'Tambahkan baris di kiri',
	insert_column_right: 'Tambahkan baris di kanan',									
	delete_column: 'Hapus kolom',									
	delete_row: 'Hapus baris',									
	delete_table: 'Hapus tabel',
	Rows: 'Baris',
	Columns: 'Kolom',	
	add_head: 'Tambah kepala',
	delete_head: 'Hapus kepala',	
	title: 'Judul',
	image_view: 'Lihat gambar',
	image_position: 'Pisisi',
	none: 'Tidak ada',
	left: 'Kiri',
	right: 'Kanan',
	image_web_link: 'Tautan gambar dari web',
	text: 'Teks',
	mailto: 'Email',
	web: 'URL',
	video_html_code: 'Kode embed video',
	file: 'Berkas',	
	upload: 'Unggah',
	download: 'Unduh',
	choose: 'Pilih',
	or_choose: 'Atau pilih',
	drop_file_here: 'Seret berkas ke sini',
	align_left:	'Rata kiri',	
	align_center: 'Rata tengah',
	align_right: 'Rata kanan',
	align_justify: 'Rata kanan kiri',
	horizontalrule: 'Garis mendatar',
	fullscreen: 'Layar penuh',
	deleted: 'Di coret',
	none: 'Tidak ada',
	anchor: 'Anchor'
};
